version: '3.3'
services:
  ppo:
    image: pelipper-post-office
    build: .
    ports:
        - "80:80"
        - "53:53"
        - "53:53/udp"
        - "27900:27900/udp"
        - "29900:29900"
    # todo: better parameterize
    command:
      - "-v"
      - "--dns-ip"
      - "192.168.178.20"
    stop_grace_period: 10s
