version: '3.3'
services:
  ppo:
    image: pelipper-post-office
    build: .
    ports:
        - "80:80"
        - "53:53"
        - "53:53/udp"
        - "27900:27900/udp"
        - "29900:29900"
    # todo: better parameterize
    command:
      - "-v"
      - "--dns-ip"
      - "192.168.178.20"
    stop_grace_period: 10s
  aptible:
    image: pelipper-post-office-https-proxy
    build: https-proxy
    environment:
      UPSTREAM_SERVERS: "ppo:80"
      FORCE_SSL: "true"
      SSL_CIPHERS: "ALL"
    ports:
      - "0.0.0.0:443:443"
    volumes:
      - './https-proxy/nas.key:/etc/nginx/ssl/server.key'
      - './https-proxy/nas.chain.crt:/etc/nginx/ssl/server.crt'
